"""add_quote_fields

Revision ID: 1ba6aca714fe
Revises: 438a1df4fb25
Create Date: 2026-06-15 17:11:49.152254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba6aca714fe'
down_revision: Union[str, None] = '438a1df4fb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_item_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price_cents', sa.Integer(), nullable=True))

    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.drop_column('quoted_at')

    with op.batch_alter_table('send_item_states', schema=None) as batch_op:
        batch_op.drop_column('unit_price_cents')

    # ### end Alembic commands ###
