"""add_dismissed_at_to_sends

Revision ID: 24b9f48e207f
Revises: 26f950d88b7d
Create Date: 2026-06-14 23:54:04.690096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b9f48e207f'
down_revision: Union[str, None] = '26f950d88b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.drop_column('dismissed_at')

    # ### end Alembic commands ###
