"""add_phone_verifications

Revision ID: 26f950d88b7d
Revises: 6c9a8203e82a
Create Date: 2026-06-14 17:56:11.308940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f950d88b7d'
down_revision: Union[str, None] = '6c9a8203e82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_verifications_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_verifications_phone'))

    op.drop_table('phone_verifications')
    # ### end Alembic commands ###
