"""add_deliver_to_inbox_to_sends

Revision ID: 2cea0b86afca
Revises: 24b9f48e207f
Create Date: 2026-06-15 04:00:15.128791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cea0b86afca'
down_revision: Union[str, None] = '24b9f48e207f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliver_to_inbox', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.drop_column('deliver_to_inbox')

    # ### end Alembic commands ###
