"""add_contacts_lists_sends

Revision ID: 6c9a8203e82a
Revises: dedf3a08f66d
Create Date: 2026-06-04 16:16:55.745900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9a8203e82a'
down_revision: Union[str, None] = 'dedf3a08f66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('linked_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'phone', name='uq_contact_owner_phone')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('custom_product_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_items_list_id'), ['list_id'], unique=False)

    op.create_table('sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sends_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sends_recipient_phone'), ['recipient_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_sends_sender_user_id'), ['sender_user_id'], unique=False)

    op.create_table('send_item_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_id', sa.Integer(), nullable=False),
    sa.Column('list_item_id', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_item_id'], ['list_items.id'], ),
    sa.ForeignKeyConstraint(['send_id'], ['sends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_item_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_send_item_states_send_id'), ['send_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_item_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_item_states_send_id'))

    op.drop_table('send_item_states')
    with op.batch_alter_table('sends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sends_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_sends_recipient_phone'))
        batch_op.drop_index(batch_op.f('ix_sends_list_id'))

    op.drop_table('sends')
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_items_list_id'))

    op.drop_table('list_items')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_owner_user_id'))

    op.drop_table('lists')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_owner_user_id'))

    op.drop_table('contacts')
    # ### end Alembic commands ###
